README.md, addon/services/ajax.js, tests/unit/services/ajax-test.js
Add documentation for host property with examples
=> Allow host to be set on ajax service

package.json
=> Make ember-cli-htmlbars a devDep.

README.md
Documents the patch method that was implemented in #21.
=> Document patch method

.jscsrc, addon/errors.js, addon/make-promise.js, addon/raw.js, addon/request.js, addon/services/ajax.js, addon/utils/parse-args.js, addon/utils/parse-response-headers.js, package.json, tests/acceptance/ajax-get-test.js, tests/dummy/app/components/ajax-get.js, tests/helpers/json.js, tests/integration/components/ajax-get-test.js, tests/integration/components/async-widget-test.js, tests/unit/errors-test.js, tests/unit/export-test.js, tests/unit/raw-test.js, tests/unit/request-test.js, tests/unit/services/ajax-test.js, tests/unit/utils/parse-args-test.js
Also updates all of the code to pass the checks
=> Add JSCS checking with ember-suave

addon/ajax-request.js, tests/acceptance/ajax-get-test.js, tests/test-helper.js, tests/unit/ajax-request-test.js
=> Handle server errors the way that Ember Data does

addon/ajax-request.js, tests/integration/components/jsonp-test.js, tests/unit/jsonp-test.js
=> Allow the wait() helper to work with JSONP

README.md, addon/ajax-request.js, tests/unit/ajax-request-test.js
=> Adds `namespace` option. Fixes #30

addon/ajax-request.js, tests/integration/components/async-widget-test.js, tests/unit/ajax-request-test.js
=> Automatically JSON-encode JSON:API requests

addon/ajax-request.js, addon/errors.js, tests/unit/ajax-request-test.js, tests/unit/error-handlers-test.js, tests/unit/errors-test.js
Adds support for the `Timeout`- and `AbortError` types that are included with Ember Data.
=> Add TimeoutError and AbortError

addon/utils/url-helpers.js, tests/unit/utils/url-helpers-test.js
=> Fix typo in RequestURL class

README.md, appveyor.yml, package.json
=> Add Appveyor configuration

addon/ajax-request.js, tests/unit/ajax-request-test.js
=> Fix memory leak in tests

addon/mixins/ajax-request.js, tests/unit/ajax-request-test.js
=> Allow configuring namespace on per-request basis

addon/mixins/ajax-request.js, addon/services/ajax.js
Closes #82
(for real this time!)
=> Remove reference to Ember Data

addon/mixins/ajax-request.js, tests/dummy/app/templates/components/ajax-get.hbs, tests/unit/ajax-request-test.js
- Adds details about expected normalized format
- Improves normalization efforts
Closes #109
=> Improve error normalization

addon/mixins/ajax-request.js, tests/unit/mixins/ajax-request-test.js
=> Revert changing payload info to `meta` property

addon/mixins/ajax-request.js, tests/unit/mixins/ajax-request-test.js
Closes https://github.com/ember-cli/ember-ajax/issues/143
=> Add isEmpty contentType check

.eslintrc.js, .jscsrc, addon/mixins/ajax-request.js, addon/mixins/ajax-support.js, bower.json, config/ember-try.js, config/environment.js, index.js, package.json, testem.js, tests/acceptance/ajax-get-test.js, tests/dummy/config/environment.js, tests/integration/components/ajax-get-test.js, tests/integration/components/async-widget-test.js, tests/unit/mixins/ajax-request-test.js
- Upgrade `ember-cli-eslint`
- Remove `ember-suave`
- Pull in `ember-suave` configuration for ESLint
- Fix files that don't pass linting
=> Upgrade linting setup, plus misc. dependency updates

addon/mixins/ajax-request.js, tests/unit/mixins/ajax-request-test.js
* Stringify application/json in additon to application/vnd.api+json
* Inspect the top-level contentType in addition to the Content-Type header
=> Stringify all json by any content-type

README.md
=> Fix typo in error handling example

package.json, yarn.lock
=> chore(package): update loader.js to version 4.2.0

addon/mixins/ajax-request.js, tests/unit/mixins/ajax-request-test.js
As per @taras [comment](https://github.com/ember-cli/ember-ajax/issues/158#issuecomment-246175431)
=> Fixes #158. Don't modify null, undefined payload

.eslintrc.js, addon/-private/promise.js, addon/-private/utils/get-header.js, addon/-private/utils/url-helpers.js, addon/errors.js, addon/mixins/ajax-request.js, addon/mixins/ajax-support.js, addon/utils/ajax.js, package.json, tests/.eslintrc.js, tests/acceptance/ajax-get-test.js, tests/acceptance/ember-data-integration-test.js, tests/dummy/app/components/ajax-get.js, tests/dummy/config/targets.js, tests/helpers/json.js, tests/integration/components/ajax-get-test.js, tests/integration/components/async-widget-test.js, tests/test-helper.js, tests/unit/-private/promise-test.js, tests/unit/-private/utils/parse-response-headers-test.js, tests/unit/mixins/ajax-request-test.js, tests/unit/mixins/legacy/normalize-error-response-test.js, tests/unit/raw-test.js, tests/unit/request-test.js, tests/unit/services/ajax-test.js, tests/unit/utils/get-header-test.js, yarn.lock
Config based on what's being introduced for new Ember apps by default.
=> Update ESLint config, includes Prettier

package.json, yarn.lock
=> Update Ember and Ember CLI

README.md
Added issue https://github.com/ember-cli/ember-ajax/issues/111 to the Readme.md file.
=> Add  namespace for a Single Request to the docs.

.travis.yml, README.md, addon/request.ts, config/ember-try.js, package.json
=> Bump minimum version

package.json, yarn.lock
=> chore(deps): update `ember-cli-babel`

addon/mixins/ajax-request.ts, package.json, tsconfig.json, types/ember-data.d.ts, yarn.lock
=> fix: bump typescript to get working d.ts

tests/unit/mixins/ajax-request-test.js
=> WIP: Investigate bug in URL building

addon/raw.ts, addon/request.ts, tests/unit/mixins/ajax-request-test.js, tests/unit/mixins/legacy/normalize-error-response-test.js, tests/unit/typescript-usage-test.ts
This throws deprecation warnings in consuming apps.
=> fix(deprecation): the new EmberObject is deprecated

.travis.yml, config/ember-try.js
Supersedes https://github.com/ember-cli/ember-ajax/pull/434
=> Add Ember 3.4 and 3.8 to Travis
