- addon/services/ajax.js
- tests/unit/services/ajax-test.js
Since the final goal of this is to become a service for making **AJAX** request, it would be a good idea not to make many assumptions about such request, **AJAX** does not necessarily mean  **json**. 
I'd like to propose we just expose the basic interface for **jQuery.ajax** without trying to be too smart about it. With this we also address issues like #2.
Also what about changing the the args of `service.request` to be ONLY `url` and `options`, I think this provides better ergonomics that the current implementation, for example if I want to do a get with query params I'd have to do something like `service.request(url, 'GET', {data: {foo: true}}` this could be reduce to `service.request(url, {data: {foo: true}}` since `GET` tends to be the default, and then if I need a different request …
> [ENHANCEMENT] Don't make assumptions about dataType and payload.

- addon/services/ajax.js
- tests/unit/services/ajax-test.js
Set the type on the options when it is not provided. This fixes the promise label seen in the inspector.
> [ENHANCEMENT] Explicitly default options type to GET

- README.md
- addon/services/ajax.js
- tests/unit/services/ajax-test.js
* `post(url, options)` - sets options.type to POST
* `del(url, options)` - sets options.type to DELETE
* `put(url, options)` - sets options.type to PUT
Added documentation and a few comments in code
> Add HTTP-verb methods on ajax service

- addon/errors.js
- addon/services/ajax.js
- tests/unit/errors-test.js
- tests/unit/services/ajax-test.js
Adds two new errors types, `BadRequestError` and `ServerError`, which correspond to `400` and `5XX` errors, respectively.
Closes #36
> Add error types for 400 and 5XX errors

- addon/ajax-request.js
- tests/unit/ajax-request-test.js
Updated version of #23 to match the new ES6 setup.  Adds tests.
> Make host option overridable

- README.md
- addon/ajax-request.js
- Re-implements `Ember.run` wrapping of handler code, as mentioned here -> https://github.com/ember-cli/ember-ajax/issues/19#issuecomment-169190521
- Adds documentation regarding run loop wrapping, as well as other general cleanup of the Readme
> Wrap request handlers in Ember run loop

- addon/ajax-request.js
- addon/utils/url-helpers.js
- tests/acceptance/ajax-get-test.js
- tests/helpers/json.js
- tests/integration/components/ajax-get-test.js
- tests/integration/components/async-widget-test.js
- tests/unit/ajax-request-test.js
- tests/unit/services/ajax-test.js
- tests/unit/utils/url-helpers-test.js
This PR ended up being a little bigger than expected; as I dug into the issue referenced in #45, I realized that the behavior of sending a one-off request to a host that didn't match the one specified in the host config options didn't actually do what I assumed it did.  So, some refactoring to be smarter about detecting the host of the request URL took place in addition to only sending the header object when the host matches the specified host, to prevent the headers from leaking through to some other host.
Closes #45
> Fix issue with always sending headers

- README.md
- addon/ajax-request.js
- tests/unit/ajax-request-test.js
Useful for SOA architectures with different domains communicating across CORS. I could have overwritten the `_shouldSendHeaders` method, but wanted a more strait forward way to tell what domains where whitelisted to pass headers too. Any feedback is much appreciated!
> Ability to  have an array of allowedHosts to set headers for.

- addon/ajax-request.js
- tests/unit/ajax-request-test.js
- tests/unit/services/ajax-test.js
Since `.get` might be used for making a `GET` request, but conflicts with Ember's API for getting properties, we can try to detect the incorrect usage and provide the user of the library with direction toward using the correct method.
Closes #51
> Help users avoid using `.get` for requests

- addon/utils/parse-response-headers.js
- tests/unit/utils/parse-response-headers-test.js
This PR fixes the same issue seen [here](https://github.com/emberjs/data/issues/4122) in Ember data. It also adds test for the `parse-response-headers` util.
> refactor parse-response-headers & add tests

- README.md
* Adds `NotFoundError`, `AbortError`, and `TimeoutError` to the list of built-in error types.
> [DOC] Update list of built-in error types

- README.md
This PR just fixes some JS Object Syntax in the README:
`{key: 'value'}` should read `{ key: 'value' }`
> fix spacing regarding JS object syntax

- addon/ajax-request.js
- addon/errors.js
- tests/unit/ajax-request-test.js
Error objects' `status` properties are always numeric, except when `AjaxRequest.normalizeErrorResponse` creates and returns its own error object, in which case it coerces the provided `status` into a string.
The result is that error handling code that needs to check status codes has to do `(status === 404 || status === '404')`, etc.
> Always return payload error status codes as strings

- README.md
I took a stab at documenting the error matching helpers, as discussed in #62.
This makes the following changes:
* Adds documentation and examples for the error helpers (e.g., `isNotFoundError`).
* Marks the helper methods on the service as public instead of private (I'm not positive but this seems like it would be desired?)
* Changes the parameter name and type to match those in `errors.js`.
> Document error matching helpers

- addon/ajax-request.js
- tests/unit/ajax-request-test.js
Since the other methods map to the HTTP type name (PATCH => `patch()`, POST => `post()`) it makes sense to do the same for `delete`. Does this sound like a good idea?
> Add a `delete` alias

- README.md
- addon/ajax-request.js
- addon/errors.js
- tests/unit/errors-test.js
Closes #90 
* Adds an `isAjaxError` helper function to match the other `is*` error helpers.
* Updates the README to mention `AjaxError` and `isAjaxError`.
* Adds test coverage for `NotFoundError`.
> isAjaxError helper

- addon/ajax-request.js
- addon/utils/ajax.js
- addon/utils/is-fastboot.js
- addon/utils/url-helpers.js
This adds basic fastboot support by using the provided `URL` module by ember-fastboot-server and [`najax`](https://github.com/najaxjs/najax).
I get warnings as `najax` does not implement `jqXHR.getAllResponseHeaders()`, but this should work for basic ajax requests.
It seems to be implemented in `najax` on the `master` (https://github.com/najaxjs/najax/pull/26) branch, I'm not sure if this is released in a npm package yet.
> Basic fastboot support

- addon/mixins/ajax-request.js
- addon/utils/url-helpers.js
- tests/unit/ajax-request-test.js
- tests/unit/utils/url-helpers-test.js
The old way of building a URL was too brittle and didn't cover a lot of the different cases that could take place, in different combinations of the host, namespace, and segment having or not having slashes included.
The new approach implemented here handles the various cases correctly, and ensures that we do not remove a trailing slash if one was provided.
> Prevent removing trailing slash in request URL

- addon/mixins/ajax-request.js
- tests/unit/ajax-request-test.js
This PR is closesly related to #79.  Since going and changing the default content type would be a breaking change, we're planning to make that happen for version `3.0`.  For the time being, this PR allows the service to set a `contentType` property that will be used by default, which itself defaults to the same value that jQuery itself would use.  This makes the default value much more explcit, which will hopefully help mitigate errors due to the default not being clear, as well as provides a clear pathway for changing the default value in the next major version.
> Add service property for default contentType

- README.md
> Document stand-alone usage

- addon/mixins/ajax-support.js
The ajax-support mixin currently calls ember-data adapter's `ajaxOptions` method which is overriden by the same mixin and calls the `options` method. But the `options` method is then again called by the ajaxService, as a result it is called twice.
To fix this ajaxOptions is not overriden anymore in the ajax-support mixin, and is
not called anymore by the ajax method, as it should not be needed by ember-ajax I think
and is a private method of the ember-data adapter.
> fix multiple calls to the options method when using the ajax-support mixin

- addon/mixins/ajax-request.js
- tests/acceptance/ember-data-integration-test.js
- tests/unit/mixins/ajax-request-test.js
If the URL given already starts with the namespace, don't both to build the URL again.  This prevents issues with Ember Data, where the URL given to the request method is pre-built.
Implements a fix for the issue reported in #139
> Fix adding namespace twice

- README.md
This addresses the concerns exposed in #167 about being able to access the full json response in case of a failed request.
> Document how to access the full response on error

- addon/mixins/ajax-support.js
- tests/acceptance/ember-data-integration-test.js
- tests/dummy/app/adapters/application.js
The AjaxSupport mixin wasn't calling the adapter's `ajaxOptions` method.
This was resulting in malformed requests for some users.
Resolves #169
> Ensure Adapter Ajax Options are Respected

- addon/mixins/ajax-request.js
The method `$.parseJSON` has been deprecated in jQuery 3+, they suggest to replace it with `JSON.parse`. This pull request does the suggested replace. This should not break any code because `JSON.parse` is supported by all major browsers and IE8+.
> Replaced $.parseJSON with JSON.parse. #159

- .travis.yml
- addon/errors.js
- addon/mixins/ajax-request.js
- package.json
- tests/unit/mixins/ajax-request-test.js
This breaking change accomplishes a few things:
* Deprecates the AjaxError#errors property. Going forward we'll do much
less with errors, and instead simply provide the payload from the
server's error response. The payload will be accessible via the
#payload property.
* Refactors Ajax Error, and friends, into ES6 classes. This is
potentially a breaking change as we no longer inherit from
Ember.Error.
Closes #175
> Refactor Error Classes

- addon/mixins/ajax-request.js
- addon/utils/get-header.js
- tests/unit/utils/get-header-test.js
Closes #184 -- tests included, all passing on my end. Covers everything on [the checklist](https://github.com/ember-cli/ember-ajax/pull/119#issuecomment-226352391), plus a bit more.
I opted for a regex check for the JSON API content type solely to get rid of `indexOf`, because I am a silly person.
> Case-insensitive header matching

- addon/mixins/ajax-request.js
The `options` object could be [frozen](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) and therefore not modifiable. It is safer to work with a clone of it. This PR does just that.
If for some reason it is not acceptable to assign to the `options` argument, let me know and I can modify this accordingly.
> Clone options object before modifying it

- .editorconfig
- .gitignore
- .npmignore
- .travis.yml
- LICENSE.md
- bower.json
- config/ember-try.js
- package.json
- testem.js
- tests/acceptance/ember-data-integration-test.js
- tests/dummy/app/app.js
- tests/dummy/app/index.html
- tests/dummy/app/router.js
- tests/dummy/config/environment.js
- tests/helpers/destroy-app.js
- tests/helpers/start-app.js
- tests/index.html
- tests/test-helper.js
- tests/unit/services/ajax-test.js
- yarn.lock
Notable changes
-----------------
* Some tests updated. I'm not entirely sure why the changes were required suddenly given that I didn't update Pretender in this pull request.
* Numerous changes to make future upgrades more ergonomic (e.g. single quotes to double quotes)
Open questions
----------------
> Upgrade Ember and Buddies to 2.10

- addon/-private/promise.js
- addon/mixins/ajax-request.js
- tests/unit/-private/promise-test.js
- tests/unit/mixins/ajax-request-test.js
A long-standing (_really_ long-standing) request of `ember-ajax` has been to provide a better way to access the XHR object created by a request without needing to use `.raw`, which only gives you the object after the fact.
This PR adds a `.xhr` object to the promise returned by making a request that can be used to inspect or manipulate the request.  This is especially useful for aborting the request after it has been kicked off, which previously has been impossible.
Closes #67
> Add XHR property to promises

- addon/mixins/ajax-request.js
I tried doing `.get('some/url')` and was scratching my head for a while..
And that I know of people don't do `object.get('my/property/with/slashes')`
> Better URL detection for .get error

- addon/errors.js
- tests/unit/errors-test.js
This only happens when the browser itself is aborting the request due to e.g. a page reload, which seems impossible to test within our test framework.
Resolves https://github.com/ember-cli/ember-ajax/issues/195
/cc @oscarni @XaserAcheron
> errors: Recognize HTTP status 0 as AbortError

- .travis.yml
- config/ember-try.js
Since we advertise Ember v1.13 compatibility, we should run Travis against it as well to make sure it really works.
> Add Ember 1.13 to Ember Try config

- addon/mixins/ajax-request.js
- addon/mixins/legacy/normalize-error-response.js
- tests/acceptance/ajax-get-test.js
- tests/dummy/app/components/ajax-get.js
- tests/dummy/app/templates/components/ajax-get.hbs
- tests/unit/mixins/ajax-request-test.js
- tests/unit/mixins/legacy/normalize-error-response-test.js
Over time, we decided that the existing `normalizeErrorResponse`
behavior tried to do way too much.  We've decided that the default
behavior should be to instead just return the error payload that the
server provides, without making modifications to it.
The old behavior can be re-introduced by including the mixin found at
`mixins/legacy/normalize-error-response`.
This also removes the deprecation warnings around the `errors` property
in favor of the replacement `payload` property.
Closes #264
> Simplify `normalizeErrorResponse`

- addon/mixins/ajax-request.js
This caused issues when we are doing `POST` requests for uploads which we may or may not specify a `contentType`. If `contentType` is false it still tries to run `.match` and you get an error.
> make sure contentType is a string before running a regex match

- addon/errors.js
- addon/mixins/ajax-request.js
- tests/unit/mixins/ajax-request-test.js
As written in #275 it would make sense to expose the actual http status codes outside of the default error classes.
Only thing I can see which blocked the PR was this: https://github.com/ember-cli/ember-ajax/pull/275#pullrequestreview-32876092
So I tried to do everything of it. Only thing I couldn't achieve is to make it a switch statement. (I don't think it's possible, cause case expects only a value and not a expression and function calls are expressions. Right??? I'm really unsure but would like to know if I'm right or not)
Happy to work some more to get it merged 👀
> Expose error codes

- fastboot-tests/helpers/server.js
- fastboot-tests/index-test.js
- package.json
I think that in some cases, the tests were being run before the Express
server had started. This should ensure that the express application
finished loading before Mocha begins executing the tests.
> fix: make FastBoot test more reliable

- addon/mixins/ajax-request.ts
- tests/unit/mixins/ajax-request-test.js
- tests/unit/services/ajax-test.js
Cases being handled here -
1) `{ host: "//", url: "/api/request" }` or `{ host: "//", url: "api/request" }`. It will generate `//api/request`
2) `{ url: "/api/request" }`. It will generate `/api/request`.
3) `{ url: "api/request" }`. It will generate `api/request`. No extra leading slash.
4) Same will happen in case of namespace. So `{ namespace: "/v1", url: "/api/request"}` will generate `/v1/api/request` and `{ namespace: "v1/", url: "/api/request" }` will generate `v1/api/request`.
> fix: don't append leading '/' when building url

- addon/mixins/ajax-request.ts
- tests/unit/mixins/ajax-request-test.js
When the namespace is present in the url, the host value being set is not taken into account. This PR fixes that issue. I have added a Test case for the scenario.
Let me know if anything else is required.
> fix: skip instead of returning url when namespace is present in url

- addon/errors.ts
They should accept any type of `AjaxError` and not the specific type they check for as this doesn't make sense.
> Fix is*Error type definitions

- tests/unit/mixins/ajax-request-test.js
I'm hoping this fixes the failures happening on `ember-beta`, since I can't reproduce the failures locally.
> chore: replace `new` with `.create()` in tests

- README.md
- addon/errors.ts
- package.json
- tests/unit/errors-test.js
- yarn.lock
> Update ember-cli-babel to version 7

- README.md
- package.json
`ember-ajax` requires and tests with Node.js 6+ but in `package.json` it says `4+`. This PR fixes that.
> Fix Node.js compatibility claim in package.json

- tests/dummy/config/targets.js
This would have made https://github.com/ember-cli/ember-ajax/issues/431 a lot more straight-forward to debug, as the issue seemed to only exist on CI and it took us a while to figure out why we did not see it locally.
/cc @rwjblue
> Always run tests in IE11 mode

- package.json
- yarn.lock
This made the fix for https://github.com/ember-cli/ember-ajax/issues/431 easier to test, but it generally seems like a good thing to keep the main, non-ember-try version pointing to the latest release.
> Update Ember.js to v3.8

- addon/mixins/ajax-request.ts
Cast types of public properties initialized to `undefined` to `undefined | <type>` so that they can be overridden without type errors.
> fix: types on public properties in ajax-request mixin

- addon/mixins/ajax-request.ts
Fixes #451.
cc @rwjblue, @Turbo87, @mike-north
> Fix deprecated usage of `run.join`

- package.json
- yarn.lock
Bump `najax` package versions to address below,
https://github.com/advisories/GHSA-fvqr-27wr-82fm
https://github.com/advisories/GHSA-35jh-r3h4-6jhm
> Update `najax` dependency

- addon/mixins/ajax-request.ts
- addon/mixins/legacy/normalize-error-response.ts
- tests/helpers/start-app.js
Because the latter is deprecated in Ember 4.
cc @Turbo87
> Resolve `ember-polyfills.deprecate-assign` deprecation warnings
